//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MyService")]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDaftService")]
public interface IDaftService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDaftService/GeneratePDF", ReplyAction="http://tempuri.org/IDaftService/GeneratePDFResponse")]
    void GeneratePDF(string url);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDaftService/GeneratePDF", ReplyAction="http://tempuri.org/IDaftService/GeneratePDFResponse")]
    System.Threading.Tasks.Task GeneratePDFAsync(string url);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDaftService/GetData", ReplyAction="http://tempuri.org/IDaftService/GetDataResponse")]
    string GetData(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDaftService/GetData", ReplyAction="http://tempuri.org/IDaftService/GetDataResponse")]
    System.Threading.Tasks.Task<string> GetDataAsync(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDaftService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IDaftService/GetDataUsingDataContractResponse")]
    MyService.CompositeType GetDataUsingDataContract(MyService.CompositeType composite);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDaftService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IDaftService/GetDataUsingDataContractResponse")]
    System.Threading.Tasks.Task<MyService.CompositeType> GetDataUsingDataContractAsync(MyService.CompositeType composite);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDaftServiceChannel : IDaftService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DaftServiceClient : System.ServiceModel.ClientBase<IDaftService>, IDaftService
{
    
    public DaftServiceClient()
    {
    }
    
    public DaftServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DaftServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DaftServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DaftServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void GeneratePDF(string url)
    {
        base.Channel.GeneratePDF(url);
    }
    
    public System.Threading.Tasks.Task GeneratePDFAsync(string url)
    {
        return base.Channel.GeneratePDFAsync(url);
    }
    
    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }
    
    public System.Threading.Tasks.Task<string> GetDataAsync(int value)
    {
        return base.Channel.GetDataAsync(value);
    }
    
    public MyService.CompositeType GetDataUsingDataContract(MyService.CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContract(composite);
    }
    
    public System.Threading.Tasks.Task<MyService.CompositeType> GetDataUsingDataContractAsync(MyService.CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContractAsync(composite);
    }
}
